### ISSUE TITLE
Pearson residual plot by year for the Triennial 

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [nwfsc-assess/VASTWestCoast#14]
It appears that the figures produced showing the Pearson residuals (both encounter and catch rate) are subset the incorrect years to plot.  As example, when the Triennial is run as a single index there are 7 panels shown in the figures, but only 3 of them appear to be referencing years with data.  Also, the "main" label for each figure is not shrunk down to fit the scale of each figure making it impossible to determine which year is being plotted.  This issue is also impacting the runs creating early and late indices, but in these instances only a single year is being plotted. Here again the main label is not informative as to which year is being shown. 

![maps--catchrate_pearson_resid](https://user-images.githubusercontent.com/6172110/58586780-b3414e80-8210-11e9-9b27-db7f5444d477.png)

**Comment by kellijohnson-NOAA** [comment]
There were two issues here,
 (1) I hard coded the size of the labels to wrongly be 1.8, they are now 0.8 with cbcd1b49f72b95a1ccf61aafd5470c32d28c5505 and
 (2) ```FishStatsUtils::plot_residuals``` did not pass ```Years2Include``` to ```FishStatsUtils::PlotMap```, which is now fixed in james-thorson-NOAA/FishStatsUtils@f6eacfdcd127463602456669f17531a8d2dae4e4
I haven't checked this for the case where the Triennial is split, but I am assuming it will work and closing it for now.

**Comment by chantelwetzel-noaa** [comment]
I am still not able to get residual plots with the correct years.  The residual plots that I am getting look the same to the one above.  So far I have tried reinstalling the FishStatsUtils package and also passing the specific years (Year_Set) in the Sim_Settings to no avail.  Please let me know if there is something that I am missing.

**Comment by kellijohnson-NOAA** [comment]
The fix was added to FishStatsUtils in a pull request that has not been merged by @James-Thorson yet, so temporarily you will have to install [my fork](https://github.com/kellijohnson-NOAA/FishStatsUtils).

**Comment by chantelwetzel-noaa** [comment]
Using your fork solves this issue. Thank you.
